apiVersion: apps/v1
kind: Deployment
metadata:
  name: getemployeename
spec:
  selector:
    matchLabels:
      app: getemployeename
  replicas: 1
  template:
    metadata:
      labels:
        app: getemployeename
    spec:
      containers:
      - env:
           - name: NODENAME
             value: A.getemployeename
           - name: PORT
             value: "8080"
           - name: BW_PROFILE
             value: docker
           - name: EMP_NAME
             value: Vinod
          image: docker.io/vinodjadhav/getemployeename
          imagePullPolicy: Always
          name: getemployeename
          ports:
            - containerPort: 8080
              protocol: TCP
