apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: getemployeename
  name: getemployeename
spec:
  replicas: 1
  selector:
    app: getemployeename
    deploymentconfig: getemployeename
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: getemployeename
        deploymentconfig: getemployeename
    spec:
      containers:
        - env:
           - name: NODENAME
             value: A.getemployeename
           - name: PORT
             value: "8080"
           - name: BW_PROFILE
             value: docker
           - name: EMP_NAME
             value: Vinod
          image: docker.io/vinodjadhav/getemployeename
          imagePullPolicy: Always
          name: getemployeename
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
