apiVersion: apps/v1
kind: Deployment
metadata:
  name: getemployeename
spec:
  selector:
    matchLabels:
      app: getemployeename
  replicas: 1
  template:
    metadata:
      labels:
        app: getemployeename
    spec:
      containers:
        - name: getemployeename
          image: docker.io/vinodjadhav/getemployeename
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODENAME
              value: A.getemployeename           # an explicit env var value
            - name: PORT
              value: "8080"              
            - name: BW_PROFILE
              value: docker
            - name: EMP_NAME
              value: Vinod