apiVersion: v1
kind: Service
metadata:
  labels:
    app: getemployeename
  name: getemployeename
spec:
  ports:
    - name: 8888-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: getemployeename
  sessionAffinity: None
  type: NodePort